// <auto-generated />
using System;
using APIFilmes.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace APIFilmes.Migrations
{
    [DbContext(typeof(APIFilmesDbContext))]
    [Migration("20210801154748_CreateLocacao")]
    partial class CreateLocacao
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("APIFilmes.Model.Filme", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<short>("Ativo")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<int>("GeneroID")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("ID");

                    b.HasIndex("GeneroID");

                    b.ToTable("Filmes");
                });

            modelBuilder.Entity("APIFilmes.Model.Genero", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<short>("Ativo")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.ToTable("Generos");
                });

            modelBuilder.Entity("APIFilmes.Model.Locacao", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CPFCliente")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<DateTime>("DataLocacao")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("Locacao");
                });

            modelBuilder.Entity("APIFilmes.Model.LocacaoItem", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("FilmeID")
                        .HasColumnType("int");

                    b.Property<int>("LocacaoID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("FilmeID");

                    b.HasIndex("LocacaoID");

                    b.ToTable("Locacao_Item");
                });

            modelBuilder.Entity("APIFilmes.Model.Filme", b =>
                {
                    b.HasOne("APIFilmes.Model.Genero", "Genero")
                        .WithMany("Filmes")
                        .HasForeignKey("GeneroID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genero");
                });

            modelBuilder.Entity("APIFilmes.Model.LocacaoItem", b =>
                {
                    b.HasOne("APIFilmes.Model.Filme", "Filme")
                        .WithMany("LocacaoItens")
                        .HasForeignKey("FilmeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("APIFilmes.Model.Locacao", "Locacao")
                        .WithMany("ItensLocacao")
                        .HasForeignKey("LocacaoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Filme");

                    b.Navigation("Locacao");
                });

            modelBuilder.Entity("APIFilmes.Model.Filme", b =>
                {
                    b.Navigation("LocacaoItens");
                });

            modelBuilder.Entity("APIFilmes.Model.Genero", b =>
                {
                    b.Navigation("Filmes");
                });

            modelBuilder.Entity("APIFilmes.Model.Locacao", b =>
                {
                    b.Navigation("ItensLocacao");
                });
#pragma warning restore 612, 618
        }
    }
}
